#!/usr/bin/env bash
# Update package index
apt update

# Install nginx
apt install -y nginx

# Set nginx to listen on port 80
sed -i 's/^listen\s*80;$/listen 80;/g' /etc/nginx/sites-available/default

# Reload nginx configuration to apply changes
nginx -s reload

# Create index.html file with desired content
echo "Holberton School" > /var/www/html/index.html
