#!/usr/bin/env bash
# Install Nginx
sudo apt update -y
sudo apt install nginx -y

# Create custom 404 page
sudo bash -c 'echo "Ceci n'"'"'est pas une page" > /var/www/html/404.html'

# Configure Nginx for custom 404 page
sudo bash -c "cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
    }
}
EOF"

# Restart Nginx to apply changes
sudo service nginx restart
